spring:
    config.activate.on-profile: dev
management:
    endpoints:
        web:
            exposure:
                include: loggers
    endpoint:
        loggers:
            enabled: true    

logging:
    # config: classpath:log4j2-spring.xml  
    level:
        root: ERROR
        com.example.log4basis.api: INFO